const FETCH_ALL_REVIEWS = "FETCH_ALL_REVIEWS";
const CREATE_REVIEW = "CREATE_REVIEW";
const UPDATE_REVIEW = "UPDATE_REVIEW";
const DELETE_REVIEW = "DELETE_REVIEW";
const AUTHENTICATION = "AUTHENTICATION";
const LOGOUT = "LOGOUT"

export {
  AUTHENTICATION, 
  LOGOUT,
  FETCH_ALL_REVIEWS,
  CREATE_REVIEW,
  UPDATE_REVIEW,
  DELETE_REVIEW};