const FETCH_ALL_CONTACTS= "FETCH_ALL_CONTACTS"
const CREATE_CONTACT= "CREATE_CONTACT";
const CREATE_FORMS = "CREATE_FORMS"
const AUTHENTICATION = "AUTHENTICATION";
const LOGOUT = "LOGOUT"

export {
  AUTHENTICATION, 
  LOGOUT,
  FETCH_ALL_CONTACTS,
  CREATE_CONTACT,
  CREATE_FORMS};